### ISSUE TITLE
CORS enabling problem.

### ISSUE THREAD

**Issue by mariobualli22** [WebThingsIO/webthing-java#19]
I am trying to connect an angular application to webthing api and i am having trouble with enabling CORS.
From what i see CORS is not enabled by default and i cannot find where to add the cross origin header.

**Comment by hobinjk** [comment]
CORS should be enabled by default here: https://github.com/mozilla-iot/webthing-java/blob/master/src/main/java/org/mozilla/iot/webthing/WebThingServer.java#L348

Are you sure you have the most up-to-date version of the code? The CORS headers were added relatively recently.

**Comment by mrstegeman** [comment]
@mariobualli22 The CORS stuff was just added last week and has not yet made it into a release version. That should happen in the very near future.

**Comment by mrstegeman** [comment]
Fixed in v0.7.0.
