### ISSUE TITLE
All websocket connections close after 5 seconds

### ISSUE THREAD

**Issue by reiballa** [WebThingsIO/webthing-java#21]
Hello! I am trying to connect to my front-end application using websocket to subscribe to one Thing. It works but it always closes after 5 seconds, as specified on this line in WebThingsServer:
`super.start(NanoHTTPD.SOCKET_READ_TIMEOUT, daemon);`
where NanoHTTPD.SOCKET_READ_TIMEOUT is 5 seconds by default.
I think there also needs to be a ping-pong implementation in the back-end to keep the connection alive. Or should i implement this on the front-end?

**Comment by hobinjk** [comment]
The gateway pings every 30 seconds so either we should use a higher delay on the order of 60 seconds or manually ping from the java side.

**Comment by mrstegeman** [comment]
A higher timeout by default would probably by good.

**Comment by reiballa** [comment]
@hobinjk ok i will try a timeout higher than 30 seconds. Thank you guys

**Comment by mrstegeman** [comment]
@reiballa You can also try to do some ping/pong from the client side. If the server side does not respond to those properly, please let us know.

**Comment by reiballa** [comment]
I just tried setting the timeout > 30 seconds and it still closes the connection.
@mrstegeman I thought about that. I will try sending a message from the front-end containing messageType and data keys. But i think we should also create a handler so the server doesn't respond with a "400 Bad Request".
Anyways i will let you know.
