### ISSUE TITLE
how to integrate these things with mozila iot gateway on Raspberry pi

### ISSUE THREAD

**Issue by prasenjeetgupta** [WebThingsIO/webthing-java#22]
I am new for mozila iot gateway can not understand how my java based web of thing integrate with mozila iot gateway and add url. I am already setup the mozila gateway in Raspberry pi and make single thing for demo purpose but confused how to deploy the Things i created. so that anyone can add this thing from mozila gateway htmlpage( UI )

Please anyone help me by complete process and with example...

thanks in advance...
https://github.com/mozilla-iot/gateway/issues/1331

**Comment by mrstegeman** [comment]
First, make sure you have the "Web Thing" add-on installed in the gateway. This can be installed via _Settings->Add-ons_, then press the + button at the bottom right, if it's not installed.

After that, you can go back to the _Things_ page from the main menu, click the + button at the bottom right. Your native web thing should be auto-detected on the network and should appear in the list of things you can add to your gateway. If it doesn't, you can click the _Add by URL..._ link at the bottom of that page and fill in the address of your thing, i.e. `http://192.168.1.20:8888/`, then click _Submit_.

**Comment by prasenjeetgupta** [comment]
can you please tell me that which Add-ons install for my own "**Smart Plug**" (with custom features ). If required to create Add-ons then how it will **create** and **add** in Mozila Gateway, so that my smart plug can be connected by Mozila Gateway.

if any video tutorials for that please give the link to understand the complete process..

**Comment by mrstegeman** [comment]
There are no additional add-ons you need to install, except for "Web Thing", aka `thing-url-adapter`. If you follow the instructions in my last comment, you should be able to add your web thing to the gateway.

**Comment by mrstegeman** [comment]
@prasenjeetgupta [This](https://hacks.mozilla.org/2018/05/creating-web-things-with-python-node-js-and-java/) may help, as well.
