### ISSUE TITLE
Build problem with Android Studio

### ISSUE THREAD

**Issue by freaktechnik** [WebThingsIO/webthing-java#26]
I added the package via the dependency manager in Android Studio, so far so good.

However Android Studio complains the following:
```
Failed to resolve: com.github.everit-org.json-schema:org.everit.json.schema:1.9.1
```

**Comment by freaktechnik** [comment]
The build config Android Studio generated looks like this: https://github.com/freaktechnik/Webthingify/blob/master/app/build.gradle#L32

**Comment by mrstegeman** [comment]
You may have to add the jitpack repo to your gradle config :
* https://github.com/everit-org/json-schema/blob/master/README.md#maven-installation
* https://www.jitpack.io/

**Comment by freaktechnik** [comment]
Adding jitpack is indeed what is required. I'm not very familiar with the java ecosystem, so not sure if this is expected to be documented. Feel free to close.

**Comment by mrstegeman** [comment]
Can you submit a PR for the README with Android Studio instructions? That would be super helpful.
