### ISSUE TITLE
Triggering action on android fails

### ISSUE THREAD

**Issue by freaktechnik** [WebThingsIO/webthing-java#31]
Actions are not properly triggered on android. The code at https://github.com/mozilla-iot/webthing-java/blob/86cd2fe7065c57a0b2271f0719fa7e42cb3d7b0c/src/main/java/org/mozilla/iot/webthing/Thing.java#L489-L502 fails with the following log:

> I/System.out: java.lang.NoSuchMethodException: <init> [class org.mozilla.iot.webthing.Thing, class org.json.JSONObject]

I couldn't find out more because adb refused to work properly after that...

**Comment by mrstegeman** [comment]
freaktechnik/Webthingify#4
