### ISSUE TITLE
Creating WebThingServer throws null pointer

### ISSUE THREAD

**Issue by smyang10** [WebThingsIO/webthing-java#48]
Following the [example](https://github.com/mozilla-iot/webthing-java/blob/master/src/main/java/org/mozilla/iot/webthing/example/SingleThing.java), I am getting a null pointer when creating the WebThingServer on Android:
~~~
server = new WebThingServer(new WebThingServer.SingleThing(thing),
                                        8888);
~~~

The error is:

> Attempt to invoke interface method 'boolean java.util.Enumeration.hasMoreElements()' on a null object reference

I can't seem to find any reason why I am getting this error. The `thing` object is created just like the example shows. Debug shows the error is being thrown in `WebThingServer.java` at the following line:
~~~
for (String address : Utils.getAddresses()) {
            this.hosts.add(address);
            this.hosts.add(String.format("%s:%d", address, this.port));
        }
~~~

**Comment by mrstegeman** [comment]
Is there a longer backtrace, by chance? It would be coming from inside `Utils.getAddresses()`, probably.

Also, what Android version and webthing-java version are you testing on?

**Comment by smyang10** [comment]
After some more digging, I found it was due to the app not being given internet access in the AndroidManifest. Once I did that it got past that error. 

However I am now finding that the minimum Android version for this appears to be 8.1 as I cannot run it on my 8.0 device.

**Comment by smyang10** [comment]
Issue was due to lack of internet access in androidmanifest
