### ISSUE TITLE
jmdns issue

### ISSUE THREAD

**Issue by jonsampson** [WebThingsIO/webthing-java#49]
Hi folks,
I've written an On/Off web thing that sends signals over 433mhz to some smart plugs in my back yard. Unfortunately they regularly crash after the first few hours running. The following log shows:
- an 11:31 PM successful send to turn off my Fountain's plug (this was probably manually triggered over the gateway UI)
- followed by a 7:00AM successful turn on signal (rule processed trigger)
- followed immediately by a death spiral where the web thing continues to run but is unable to be properly interacted with from the Gateway.

```
2019-07-29 23:31:18 - [INFO] rpi-rf_send: XXXXXXX [protocol: 1, pulselength: 314, length: default, repeat: 10]
Mon Jul 29 23:31:19 EDT 2019 - Fountain thing On-State is now false (exit value 0)
2019-07-30 07:00:00 - [INFO] rpi-rf_send: YYYYYYY [protocol: 1, pulselength: 314, length: default, repeat: 10]
Tue Jul 30 07:00:00 EDT 2019 - Fountain thing On-State is now true (exit value 0)
[JmDNS(mysubdomain-mydomain-biz.local.).State.Timer] WARN javax.jmdns.impl.tasks.state.DNSStateTask - Renewer(mysubdomain-mydomain-biz.local.).run() exception 
java.io.IOException: Invalid argument (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1634)
	at javax.jmdns.impl.tasks.state.DNSStateTask.run(DNSStateTask.java:131)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
[mysubdomain-mydomain-biz.local..recover()] WARN javax.jmdns.impl.JmDNSImpl - RECOVERING
[JmDNS(mysubdomain-mydomain-biz.local.).State.Timer] WARN javax.jmdns.impl.tasks.state.DNSStateTask - Canceler(mysubdomain-mydomain-biz.local.).run() exception 
java.io.IOException: Invalid argument (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1634)
	at javax.jmdns.impl.tasks.state.DNSStateTask.run(DNSStateTask.java:131)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
[mysubdomain-mydomain-biz.local..recover()] WARN javax.jmdns.impl.DNSStatefulObject$DefaultImplementation - Wait for canceled timed out: DNS: mysubdomain-mydomain-biz.local. [mysubdomain-mydomain-biz/my.internal.ip] state: canceling 1 task: null
[mysubdomain-mydomain-biz.local..recover()] WARN javax.jmdns.impl.DNSStatefulObject$DefaultImplementation - Wait for canceled timed out: DNS: mysubdomain-mydomain-biz.local. [mysubdomain-mydomain-biz/my.internal.ip] state: canceling 1 task: null
[mysubdomain-mydomain-biz.local..recover()] WARN javax.jmdns.impl.JmDNSImpl - mysubdomain-mydomain-biz.local..recover() Could not recover we are Down!
```
It's a bit maddening as Google hasn't turned up much useful.

Maybe it has something to do with the web socket ping (line 732 below)? By no means am I sure:

https://github.com/mozilla-iot/webthing-java/blob/4fe7bc57dd48e49392a921dc6c9a493c9bea69ed/src/main/java/org/mozilla/iot/webthing/WebThingServer.java#L697-L747

**javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1634)**:
https://github.com/jmdns/jmdns/blob/d15acaf8ad5f11fc6a1dfa597e3e36803a332dbd/src/main/java/javax/jmdns/impl/JmDNSImpl.java#L1600-L1637

Any guidance would be greatly appreciated. Please let me know if I can provide more info.

- Gateway was flashed to an SD card. I enabled developer access and am running two web things on different ports in the 8000 range.
- DNS is managed via Route53. The subdomain for the web things points to the home network internal IP of the Raspberry Pi which also runs the Gateway.

Maven dep:
```xml
		<dependency>
			<groupId>org.mozilla.iot</groupId>
			<artifactId>webthing</artifactId>
			<version>0.12.0</version>
		</dependency>
```

Thank you.

**Comment by mrstegeman** [comment]
Hmmm, that's definitely a problem. This is not a WebSocket issue, though, but rather an issue in jmdns (the mDNS server). Specifically, the crash is here: https://github.com/jmdns/jmdns/blob/d15acaf8ad5f11fc6a1dfa597e3e36803a332dbd/src/main/java/javax/jmdns/impl/tasks/state/DNSStateTask.java#L131

I'm guessing that is the task that periodically sends out the mDNS broadcast. Is it possible that your thing is losing network connectivity? That would cause the `send()` to fail.

**Comment by jonsampson** [comment]
Anything is possible when Xfinity wifi is involved! I'll poke around in that direction and get back to you on the weekend when I have time to hack. 

Thank you so much for the quick response!

**Comment by jonsampson** [comment]
Small update:

I reset everything to green state last night. I installed smokeping to track google.com and turned off `power_saving` on the wlan0 interface. This morning things were still working! As of 1PM things still seemed available from the gateway (although I'm not home to verify). If things continue to go well over the next few days I'll uninstall smokeping and see how the `power_saving` setting alone goes. Cheers.

**Comment by mrstegeman** [comment]
That sounds promising!

**Comment by jonsampson** [comment]
Crashes resumed on Friday after disabling the smokeping service. Re-enabling on Saturday has not has had the same initial effect - crashes into Sunday. Smokeping graphs do indeed show instances where 19/20 pings don't come back which supports your diagnosis. I haven't gone so far to correlate the graphs to instances where the web things die, but I think it's enough to go on. :1st_place_medal: 

So... in my iffy network environment, jmDNS hangs up. I can pursue this in a few ways that immediately occur to me:
1) Reinitialize jmDNS when a failure state is noted by the web thing (if possible) or,
2) Check on the [recovery jmDNS is attempting](https://github.com/jmdns/jmdns/blob/d15acaf8ad5f11fc6a1dfa597e3e36803a332dbd/src/main/java/javax/jmdns/impl/JmDNSImpl.java#L1824-L1859) and turn some knobs.
3) Perhaps a wifi extender. This is the least interesting to me! :smile_cat:

Alternately, I may be off base!

Do you have any thoughts re: point 1? If that's not something appropriate, I think we can probably close this issue with my great thanks to you.

**Comment by mrstegeman** [comment]
I would gladly accept a PR that fixes the jmDNS issue on this library's side, if you can manage it!

I wonder if you can implement a Delegate for the IO error:
* https://github.com/jmdns/jmdns/blob/d15acaf8ad5f11fc6a1dfa597e3e36803a332dbd/src/main/java/javax/jmdns/JmDNS.java#L27-L39
* https://github.com/jmdns/jmdns/blob/d15acaf8ad5f11fc6a1dfa597e3e36803a332dbd/src/main/java/javax/jmdns/JmDNS.java#L449

**Comment by jonsampson** [comment]
Just a short update to this: I haven't had any luck with the [`Delegate` method](https://github.com/jonsampson/webthing-java/commit/58f4df3cc268733294099215a19b3cf1f15ca7bb); unfortunately it doesn't appear to be invoked when the "sendto failed" error occurs. I'm currently investigating whether running two separate webthings on the same RPi might be causing an issue with simultaneous attempts to access the same socket. I've read a few things now which point in that direction (although I've read a few more that say multithreaded socket access is just fine). :crying_cat_face: 

I'll just be running the one thing and observing behavior. I'm fairly confident that the Gateway doesn't employ any MDNS of its own to announce itself. I did not note any packets when using Wireshark. Can you confirm that?

Cheers.

**Comment by mrstegeman** [comment]
When you say 2 separate webthings, do you mean 2 entirely separate instances of this library? If so, that would probably cause issues. If you're just using the `MultipleThings` class, you should be fine.

As for the gateway... it's complicated. On Raspbian, we rely on avahi-daemon to do mDNS announcements for us. On OpenWrt, we use whichever responder is installed. On other platforms, the gateway _does_ have a built-in [mDNS responder](https://github.com/mozilla-iot/gateway/blob/master/src/mdns-server.js). However, the gateway is not announced as a webthing itself (for various reasons). We only use mDNS to announce the hostname, such that `gateway.local` can be resolved.

**Comment by tim-hellhake** [comment]
@jonsampson is this still relevant?

**Comment by jonsampson** [comment]
Hi Tim. I stopped work on this project so we can close this!
