### ISSUE TITLE
Double properties will not be updated when json input is provided as integer

### ISSUE THREAD

**Issue by bw-hro** [WebThingsIO/webthing-java#62]
Some http clients automatically transform json request body like {"myDoubleProperty":123.0} to {"myDoubleProperty":123} which conforms to the json standard but makes type checking for Java harder.

Webhing Java implementation should support both input variants for double properties. At the moment the following response will be produced:

```
PUT  http://my-webthing-server/properties/myDoubleProperty
{"myDoubleProperty":123}

--

500 

Error: java.lang.ClassCastException : class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')

```

I experienced the same issue for my CPP implementation of Webthings (https://github.com/bw-hro/webthing-cpp) and manged to solve it: In case it might help also cf. https://github.com/bw-hro/webthing-cpp/issues/3

As this respository seems to be not active I wonder if a merge request would be welcome or if maybe one of the  original project members is willing to look into this issue?

Anyway thanks for the work of creating the Webthing framework.

**Comment by benfrancis** [comment]
Hi @bw-hro, thank you for reporting. PRs are still welcome.

Note that although JSON does not distinguish between integers and floating-point numbers, JSON Schema does have distinct `integer` and `number` types. If the the `type` member of a [Property](https://webthings.io/api/#property-object) in a Thing Description is set to "integer", then I would assume the web thing should cast any input values to an integer. If it's set to "number", then it should be able to accept values with our without a fractional part but can _probably_ safely cast them to a float or double?

What approach did your solution take?
