### ISSUE TITLE
Perform release v0.15.0

### ISSUE THREAD

**Issue by bw-hro** [WebThingsIO/webthing-java#65]
Hello,

preparation of release v0.15.0 was successfully done with merge request #64. To make changes available for users via maven central, a release needs to be performed. It seems that adding a tag 'v0.15.0' would be enough and github workflow would do the rest. As I have no rights to push tags, can you @benfrancis as official maintainer (right?) create this tag please?

Thank you very much. In case anything prevents the new release, that I could work on, please let me know.

Best Regards, Benno

**Comment by benfrancis** [comment]
Am I right in thinking this has been done now? https://github.com/WebThingsIO/webthing-java/releases/tag/v0.15.0

**Comment by bw-hro** [comment]
Hi,
I think work is done only half. Release tag is set but release workflow script failed. So we now have sources in correct state but results were not published to maven central.

also cf. https://central.sonatype.com/search?q=g:io.webthings%20%20a:webthing&smo=true
and the button in readme.md

The actions says that it can not perform the maven deploy command.
https://github.com/WebThingsIO/webthing-java/actions/runs/7240668950/job/19723910108

from action log:

gpg: no default secret key: No secret key
gpg: signing failed: No secret key
Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project webthing:

so maybe credentials for the action are not up to date anymore? Unfortunately I have no experience with maven central deployment and no admin access to this repository to play around with it.   

In case I can help just let me know.

**Comment by bw-hro** [comment]
@benfrancis any update how to sync this repository with maven central?

**Comment by benfrancis** [comment]
@tim-hellhake Do you know what needs updating here?

I have a vague recollection about a Maven Central account that Mike passed over the details for which you may also have access to. I just tried to use their Forgotten Password feature with team@webthings.io to see if I can generate a new key, but so far no luck.

Let me know if there's anything I can do to help.

**Comment by benfrancis** [comment]
I've managed to gain access to the WebThingsIO account on oss.sonatype.org where I believe this is published.

A mutual friend pointed out to me that the [Maven GitHub action](https://github.com/samuelmeuli/action-maven-publish) currently used by the release workflow in this repo was archived in January last year and may need updating to a different one.

I can generate a new "Access User Token" via the oss.sonatype.org web interface (which would invalidate the old one), but I think that's separate to the GPG key used to sign releases, which as I understand it will have been generated locally and then uploaded to GitHub (where it still stored as far as I can tell). The current GitHub Action doesn't seem to be able to find the key.

@tim-hellhake I can give you access to the Nexus Repository Manager at oss.sonatype.org again if that helps.

**Comment by bw-hro** [comment]
@benfrancis, @tim-hellhake  any news on this issue? Anything I can help with to finalize it?

**Comment by benfrancis** [comment]
@bw-hro No news I'm afraid. A next step might be to find a replacement maven GitHub action to fix the release workflow?

**Comment by bw-hro** [comment]
@benfrancis  How about this one?

 https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#publishing-using-apache-maven  

The 'setup-java' action is already used as part of the current release action and seems to be actively maintained.

**Comment by benfrancis** [comment]
@tim-hellhake What do you think?

**Comment by tim-hellhake** [comment]
One problem might be that our key is expired:

![image](https://github.com/WebThingsIO/webthing-java/assets/17127122/64b44982-be8c-4deb-9761-2917013da229)

**Comment by tim-hellhake** [comment]
![image](https://github.com/WebThingsIO/webthing-java/assets/17127122/dff70346-ccc0-4281-aaa1-0db4e0d45512)

@benfrancis
Did you reset the password in the process?
Could you please generate a user token and replace the `NEXUS_PASSWORD` secret?

**Comment by tim-hellhake** [comment]
@benfrancis
I generated a new gpg key which expires in 2 years.
The password should be the only problem now.

**Comment by tim-hellhake** [comment]
According to the logs the signing process seems to work.

**Comment by benfrancis** [comment]
@tim-hellhake thanks for doing this.

I think I know what the Maven password is, do you still need me to update it?

**Comment by tim-hellhake** [comment]
@benfrancis
Yes, the current one doesn't seem to work.

**Comment by benfrancis** [comment]
@tim-hellhake I've sent you an email.

**Comment by tim-hellhake** [comment]
@benfrancis
The credentials seem work now.
I uploaded the gpg key to keys.openpgp.org.
You should have received a verification email to team@webthings.io by now.
After confirming the key restarting the failed job should be enough.

**Comment by tim-hellhake** [comment]
@benfrancis
The credentials seem work now.
I uploaded the gpg key to keys.openpgp.org.
You should have received a verification email to [team@webthings.io](mailto:team@webthings.io) by now.
After confirming the key, restarting the failed job should be enough.

**Comment by tim-hellhake** [comment]
@benfrancis
The credentials seem to work now.
I uploaded the gpg key to keys.openpgp.org.
You should have received a verification email to team@webthings.io by now.
After confirming the key, restarting the failed job should be enough.

**Comment by benfrancis** [comment]
I don't think it worked https://github.com/WebThingsIO/webthing-java/actions/runs/9017739530/job/24779294646

**Comment by tim-hellhake** [comment]
The old v0.15.0 release still existed.
I had to delete it first.
https://oss.sonatype.org/service/local/repositories/releases/content/io/webthings/webthing/0.15.0/webthing-0.15.0.jar

**Comment by tim-hellhake** [comment]
@bw-hro Would you mind trying it out?

**Comment by bw-hro** [comment]
I can confirm, that correct version is downloaded from maven central when specifying 0.15.0 release in pom by following entry:

```
<dependency>
    <groupId>io.webthings</groupId>
    <artifactId>webthing</artifactId>
    <version>0.15.0</version>
</dependency>
```
Successfully checked that this version can handle integers as input for  ``Value<Double>``type. 

so it seems from my point of view, that we are done. Thanks all of you for your efforts. Just let me know, in case additional tests are required

**Comment by benfrancis** [comment]
Thank you both for your work on this.
